-   id: crlf-to-lf
    name: crlf-to-lf
    description: Replaces CRLF with LF!
    entry: crlf-to-lf
    language: python
    always_run: true
    pass_filenames: true
-   id: pytest-check
    name: pytest-check
    description: This hook runs pytest before committing.
    entry: pytest-check
    language: python
    always_run: true
    pass_filenames: false
